// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.5
// source: recachepb.proto

package recachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReCache_Get_FullMethodName = "/api.ReCache/Get"
)

// ReCacheClient is the client API for ReCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type reCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewReCacheClient(cc grpc.ClientConnInterface) ReCacheClient {
	return &reCacheClient{cc}
}

func (c *reCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ReCache_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReCacheServer is the server API for ReCache service.
// All implementations must embed UnimplementedReCacheServer
// for forward compatibility
type ReCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedReCacheServer()
}

// UnimplementedReCacheServer must be embedded to have forward compatible implementations.
type UnimplementedReCacheServer struct {
}

func (UnimplementedReCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedReCacheServer) mustEmbedUnimplementedReCacheServer() {}

// UnsafeReCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReCacheServer will
// result in compilation errors.
type UnsafeReCacheServer interface {
	mustEmbedUnimplementedReCacheServer()
}

func RegisterReCacheServer(s grpc.ServiceRegistrar, srv ReCacheServer) {
	s.RegisterService(&ReCache_ServiceDesc, srv)
}

func _ReCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReCache_ServiceDesc is the grpc.ServiceDesc for ReCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ReCache",
	HandlerType: (*ReCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ReCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recachepb.proto",
}
